language: cpp
dist: trusty
git:
  submodules: false
before_install:
  - add-apt-repository --yes ppa:beineri/opt-qt571-trusty
  - add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - apt-get update -qq
  - apt-get install -qq g++-4.8 libsamplerate0-dev libquazip0-dev
  - apt-get install -qq -y qt57base qt57declarative qt57imageformats qt57location qt57multimedia qt57quickcontrols qt57script qt57svg qt57tools qt57translations libsdl2-dev
  - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
  - chmod +x cmake-3.7.2-Linux-x86_64.sh
  - mkdir cmake-bin
  - ./cmake-3.7.2-Linux-x86_64.sh --skip-license --prefix=`pwd`/cmake-bin
script:
  - source /opt/qt57/bin/qt57-env.sh
  - mkdir phoenix-build
  - cd phoenix-build
  - ../cmake-bin/bin/cmake ..
  - make -j2
notifications:
  irc:
    channels:
      - "chat.freenode.net#phoenix-dev"
    use_notice: true
    skip_join: true
